#!/usr/bin/python

def createHeader(title):
  print "Content-Type: text/html"
  print
  print "<html lang=\"en\">"
  print "<head>"
  print "  <title>" + title + "</title>"
  print "  <meta charset=\"utf-8\">"
  print "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=yes\">"
  print "  <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css\">"
  print "  <link rel=\"stylesheet\" href=\"http://www.w3schools.com/lib/w3.css\">"
  print "  <link rel=\"stylesheet\" href=\"css/w3-theme-green.css\">"
  print "  <link rel=\"stylesheet\" href=\"css/sidburgh.css\">"
  print "  <link rel=\"stylesheet\" href=\"http://visualidiot.com/files/real-world.css\">"
  print "  <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>"
  print "  <script src=\"https://code.jquery.com/ui/1.12.0/jquery-ui.js\"></script>"
  print "  <script src=\"https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js\"></script>"
  print "  <script src=\"https://cdn.datatables.net/1.10.12/js/dataTables.jqueryui.min.js\"></script>"
  print "  <script src=\"http://www.tablesorter.com/__jquery.tablesorter.js\"></script>"
  print "  <script>"
  print "    $( function() {"
  print "      $( \"#accordion\" ).accordion();"
  print "      $( \"#tabs\" ).tabs();"
  print "      $( \"input\" ).checkboxradio();"
  print "      $( \"fieldset\" ).controlgroup();"
  print "      $( \"#stats\" ).tablesorter();"
  print "      $( \"#dialog\" ).dialog( {width:'auto', autoOpen: false}  );"
  print "    } );"
  print "  </script>"
  print "</head>"
  print "<body>"

def createNavigation():
  print "<div>"
  print "<ul class=\"topnav\" id=\"myTopnav\">"
  print "<li><a href=\"standings.py\">Standings</a></li>"
  print "<li><a href=\"scores.py\">Scores</a></li>"
  print "<li><a href=\"stats.py\">Stats</a></li>"
  print "<li><a href=\"history.py\">History</a></li>"
  #print "<li class=\"icon\">"
  #print "<a href=\"javascript:void(0);\" onclick=\"\">&#9776;</a>"
  #print "</li>"
  print "</ul>"
  print "</div>"

def createFooter():
  print "</body>"
  print "</html>"

